2024-12-17 20:30:30,915 - INFO - Continuing processing from course 1 of 1691
2024-12-17 20:32:19,874 - ERROR - Error processing https://kurser.dtu.dk/course/02427: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:32:19,874 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/f4cef7bf-9ee1-455f-a48a-4b0f088af685
2024-12-17 20:32:19,876 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/af688e19-179a-4ece-badf-4f3a927de6d2
2024-12-17 20:32:19,878 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc97b6c8b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f4cef7bf-9ee1-455f-a48a-4b0f088af685
2024-12-17 20:32:19,879 - ERROR - Error processing https://kurser.dtu.dk/course/02426: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:32:19,880 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc97b6cc40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/af688e19-179a-4ece-badf-4f3a927de6d2
2024-12-17 20:32:19,887 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc97b711f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f4cef7bf-9ee1-455f-a48a-4b0f088af685
2024-12-17 20:32:19,897 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc97b73520>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/af688e19-179a-4ece-badf-4f3a927de6d2
2024-12-17 20:32:58,935 - INFO - Continuing processing from course 1 of 1691
2024-12-17 20:34:28,575 - ERROR - Error processing https://kurser.dtu.dk/course/02322: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:34:28,576 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/49623b93-dd2d-445e-870b-87e2d06d4dd6
2024-12-17 20:34:28,578 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30671b9100>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcd7948c-318f-4f58-bbc5-0bcf1ef5e8b7
2024-12-17 20:34:28,580 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f308085c130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcd7948c-318f-4f58-bbc5-0bcf1ef5e8b7
2024-12-17 20:34:28,580 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f30808578e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/49623b93-dd2d-445e-870b-87e2d06d4dd6
2024-12-17 20:34:28,581 - ERROR - Error processing https://kurser.dtu.dk/course/02323: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:34:28,588 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3080857ca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bcd7948c-318f-4f58-bbc5-0bcf1ef5e8b7
2024-12-17 20:34:28,590 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f308085ffd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/49623b93-dd2d-445e-870b-87e2d06d4dd6
2024-12-17 20:34:28,601 - ERROR - Error processing https://kurser.dtu.dk/course/02321: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:34:55,591 - INFO - Continuing processing from course 1 of 1691
2024-12-17 20:35:36,794 - ERROR - Error processing https://kurser.dtu.dk/course/02116: list index out of range
2024-12-17 20:35:50,057 - ERROR - Error processing https://kurser.dtu.dk/course/02161: list index out of range
2024-12-17 20:35:54,249 - ERROR - Error processing https://kurser.dtu.dk/course/02191: list index out of range
2024-12-17 20:36:05,828 - ERROR - Error processing https://kurser.dtu.dk/course/02233: list index out of range
2024-12-17 20:36:34,736 - ERROR - Error processing https://kurser.dtu.dk/course/02329: list index out of range
2024-12-17 20:36:47,456 - ERROR - Error processing https://kurser.dtu.dk/course/02421: list index out of range
2024-12-17 20:36:57,459 - ERROR - Error processing https://kurser.dtu.dk/course/02456: list index out of range
2024-12-17 20:37:57,306 - ERROR - Error processing https://kurser.dtu.dk/course/10063: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:37:57,307 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/e38e6abc-51a5-464e-acbc-7128f7ecd33f
2024-12-17 20:37:57,309 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3125598f70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f5aa2144-ba2f-4880-b0c8-8dd88d627209
2024-12-17 20:37:57,312 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3126af2100>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e38e6abc-51a5-464e-acbc-7128f7ecd33f
2024-12-17 20:37:57,312 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f311e061a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f5aa2144-ba2f-4880-b0c8-8dd88d627209
2024-12-17 20:37:57,313 - ERROR - Error processing https://kurser.dtu.dk/course/10060: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:37:57,314 - ERROR - Error processing https://kurser.dtu.dk/course/10054: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:37:57,315 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f311e061b80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e38e6abc-51a5-464e-acbc-7128f7ecd33f
2024-12-17 20:37:57,324 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f312414c0a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f5aa2144-ba2f-4880-b0c8-8dd88d627209
2024-12-17 20:37:57,344 - ERROR - Error processing https://kurser.dtu.dk/course/10037: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:38:34,349 - INFO - Continuing processing from course 1 of 1691
2024-12-17 20:39:31,912 - ERROR - Error processing https://kurser.dtu.dk/course/02180: list index out of range
2024-12-17 20:39:39,982 - ERROR - Error processing https://kurser.dtu.dk/course/02209: list index out of range
2024-12-17 20:39:41,194 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/6fe5034e-32c4-4049-a5f8-8637a9916d0a
2024-12-17 20:39:41,199 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff4c6f6c9a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9e79baf-a298-48fc-acef-9518414e2ff0
2024-12-17 20:39:41,200 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff4c6f71130>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9e79baf-a298-48fc-acef-9518414e2ff0
2024-12-17 20:39:41,200 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff4c6f6c8e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6fe5034e-32c4-4049-a5f8-8637a9916d0a
2024-12-17 20:39:41,200 - ERROR - Error processing https://kurser.dtu.dk/course/02233: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:39:41,201 - ERROR - Error processing https://kurser.dtu.dk/course/02232: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:39:41,202 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff4c6f6c880>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9e79baf-a298-48fc-acef-9518414e2ff0
2024-12-17 20:39:41,202 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff4c6f712b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6fe5034e-32c4-4049-a5f8-8637a9916d0a
2024-12-17 20:39:41,209 - ERROR - Error processing https://kurser.dtu.dk/course/02226: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-12-17 20:48:04,847 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /session/e862ded1-65db-4848-bba8-249b1d8cbf11
2024-12-17 20:48:04,848 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa913da8580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e862ded1-65db-4848-bba8-249b1d8cbf11
2024-12-17 20:48:04,849 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa913da8790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/e862ded1-65db-4848-bba8-249b1d8cbf11
